print pdf code
Michelle-Lohwt/student-course-registration-system pull request #10
Opened 2022-01-10 10:47 UTC by ziqiang2344

removed unwanted jar files
inserted jar files for output pdf
inserted code for output pdf at classes/Student.java

2022-01-10 11:55 UTC, YouQuan2007 reviewed
the "test.pdf" in line 19 is created by ourselves?

2022-01-11 00:05 UTC, Michelle-Lohwt commented on src/sample/classes/Student.java
> +        String path = "Desktop/test.pdf";
try to change the name of the pdf to something more understandable

2022-01-11 00:06 UTC, Michelle-Lohwt requested changes
try to change the name of the pdf to something more understandable

2022-01-11 02:50 UTC, ziqiang2344 commented
> the "test.pdf" in line 19 is created by ourselves?

it's auto generated

2022-01-11 03:12 UTC, Michelle-Lohwt approved these changes

2022-01-11 03:45 UTC, YouQuan2007 approved these changes

2022-01-11 03:47 UTC, merged