added directory selector
Michelle-Lohwt/student-course-registration-system pull request #13
Opened 2022-01-13 19:01 UTC by ziqiang2344

2022-01-14 00:42 UTC, Michelle-Lohwt reviewed
@ziqiang2344 can you put up a video to show what these 2 files doing?

2022-01-14 02:42 UTC, ziqiang2344 commented
> @ziqiang2344 can you put up a video to show what these 2 files doing?

Yes sure, will do it once I complete this code. Haven't finish ammendment

2022-01-14 19:21 UTC, ziqiang2344 commented
@Michelle-Lohwt @YouQuan2007  I tried output the file path from the controller to txt and input the path as string in the Student.java. However, the output txt was not successful. Do you mind to help me check where could have been wrong? Thank you.

2022-01-15 01:05 UTC, Michelle-Lohwt commented
Can you upload a video, cuz I cannot see what's the problem from the code

2022-01-15 01:14 UTC, YouQuan2007 reviewed
yes i agree with michelle, a video would be better in explaining the problems

2022-01-15 14:29 UTC, Michelle-Lohwt commented
So far I haven't see a video @ziqiang2344

2022-01-16 01:14 UTC, Michelle-Lohwt commented on filepath.txt
> +C:\Users\user\Downloads
What is this?

2022-01-16 01:14 UTC, Michelle-Lohwt commented on src/sample/classes/Student.java
> +        //input the text file for the course list
remove unecessary comments

2022-01-16 01:15 UTC, Michelle-Lohwt requested changes
Check the comments

2022-01-16 10:36 UTC, Michelle-Lohwt commented on src/sample/classes/Student.java
>  public class Student {
so basically, no need this class?

2022-01-16 10:37 UTC, Michelle-Lohwt commented on src/sample/classes/StudentController.java
> +        //input the text file for the course list
the comments are still here though

2022-01-16 10:38 UTC, Michelle-Lohwt commented on src/sample/classes/StudentController.java
> +public void initialize(URL url, ResourceBundle rb){
is initialize a must, if no, can remove it

2022-01-16 10:38 UTC, Michelle-Lohwt commented on src/sample/courseRegController.java
> +   //switchTo(event,"classes/Student.fxml");
remove unnecessary comments

2022-01-16 10:58 UTC, Michelle-Lohwt approved these changes

2022-01-16 11:03 UTC, merged